---

server:
    port: 8080

security:
    basic:
        enabled: true
    oauth2:
        resource.filter-order: 3

spring:
    datasource:
        driver-class-name: @jdbc.driver@
        url: @jdbc.url@
        name:
        username: @jdbc.user@
        password: @jdbc.password@
        initialize: true

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 20MB
            max-request-size: 25MB
            location: ""